version: '3.8'

services:
  postgres:
    build:
      context: ./database
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 10s
      retries: 5

  ticket-registry-app:
    build:
      context: ./ticket-registry
    container_name: ticket-registry-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - mynetwork

  payment-app:
    build:
      context: ./payment
    container_name: payment-service
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  book-ticket-app:
    build:
      context: ./book-tickets
    container_name: book-tickets-container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data_volume:
