version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  ticket-registry-app:
    build:
      context: ./ticket-registry
    container_name: ticket-registry-service
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - mynetwork

  payment-app:
    build:
      context: ./payment
    container_name: payment-app-container
    ports:
      - "8081:8081"
    networks:
      - mynetwork

  book-ticket-app:
    build:
      context: ./book-tickets
    container_name: book-tickets-container
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    networks:
      - mynetwork

networks:
  mynetwork:
